### ISSUE TITLE
Implement support for configuration from a file

### ISSUE THREAD

**Issue by arax** [EGI-FCTF/rOCCI-cli#6]
Implement support for a profile-based configuration loaded from YAML files, mainly for authentication details and endpoint information.

``` yaml
# rOCCI-cli configuration
default: &default
  auth: x509
  voms: true
  user-cred: /tmp/x509_1001

profile1:
  <<: *default
  endpoint: https://example1.occi.example.org:11443/

profile2:
  <<: *default
  endpoint: https://example2.occi.example.org:11443/
```

``` bash
$ occi --profile profile2 --action describe --resource compute
```
